# Exercice 1

In [79]:
from PIL import *

### Question 1 :

In [80]:
# France

size = (106,190)
imgFranceBlue = Image.new('RGB',size,"blue")
imgFranceWhite = Image.new('RGB',size,"white")
imgFranceRed = Image.new('RGB',size,"red")
 
imgFrance = Image.new('RGB', (318,190))
 
imgFrance.paste(imgFranceBlue, (0,0))
imgFrance.paste(imgFranceWhite, (106,0))
imgFrance.paste(imgFranceRed, (212,0))
 
imgFrance = ImageOps.expand(imgFrance, border=1, fill='black')
imgFrance.save("france", "PNG")
imgFrance.show()

In [81]:
# Italie

size = (106,190)
imgItalieGreen = Image.new('RGB',size,"green")
imgItalieWhite = Image.new('RGB',size,"white")
imgItalieRed = Image.new('RGB',size,"red")
 
imgItalie = Image.new('RGB', (318,190))
 
imgItalie.paste(imgItalieGreen, (0,0))
imgItalie.paste(imgItalieWhite, (106,0))
imgItalie.paste(imgItalieRed, (212,0))
 
imgItalie = ImageOps.expand(imgItalie, border=1, fill='black')
imgItalie.save("italie", "PNG")
imgItalie.show()

### Question 2 :

In [82]:
imgNoirBlanc = Image.open('image1.jpg')
imgNoirBlanc = imgNoirBlanc.convert('L')
imgNoirBlanc = imgNoirBlanc.point(lambda p: p > 128 and 255)
imgNoirBlanc.show()

### Question 3 :

In [83]:
imgNoirBlanc = Image.open('image1.jpg')
imgNoirBlanc = imgNoirBlanc.convert('LA')
imgNoirBlanc.show()

### Question 4 :

In [84]:
imgReverse = Image.open('image1.jpg')
imgReverse = ImageOps.mirror(imgReverse)
imgReverse.show()

### Question 5 :

In [111]:
img4 = Image.open('image1.jpg')
smallSize = int((img4.size)[0]/2), int((img4.size)[1]/2) 
smallImage = img4.resize(smallSize)
imgFinal = Image.new('RGB', img4.size)
imgFinal.paste(smallImage, (0,0))
imgFinal.paste(smallImage, (smallSize[0],0))
imgFinal.paste(smallImage, (0,smallSize[1]))
imgFinal.paste(smallImage, (smallSize[0],smallSize[1]))
imgFinal.show()

### Question 6 :

In [116]:
def assombrir(img):
    img = img.point(lambda p: (p/2))
    return img

assombrir(Image.open('image1.jpg')).show()

In [118]:
def eclaircir(img):
    img = img.point(lambda p: (p*2))
    return img

eclaircir(Image.open('image1.jpg')).show()

# Exercice 3 :

In [145]:
from matplotlib.image import imread
import numpy as np


### Question 1 :

In [130]:
I1 = imread('pitre.bmp')
I2 = imread('pitre2.bmp')

print(I1)
print(I2)

# La matrice I1 est composé de matrice de taille x*3, alors que la matrice I2 est composé de grosse matrice de x*255.

[[[122  26  40]
  [127  65  74]
  [124  31  52]
  ...
  [166  42  43]
  [169  66  54]
  [168  98 102]]

 [[124  33  42]
  [130  65  77]
  [127  39  61]
  ...
  [168  50  47]
  [167  65  59]
  [168  97  97]]

 [[126  38  46]
  [125  68  80]
  [123  43  59]
  ...
  [169  61  33]
  [172  66  54]
  [169  95  99]]

 ...

 [[ 87   6  26]
  [ 88   5  14]
  [ 83   8  31]
  ...
  [199 183 149]
  [202 184 151]
  [204 184 149]]

 [[ 86   7  29]
  [ 86   3  21]
  [ 86   7  29]
  ...
  [202 185 149]
  [202 184 144]
  [204 184 144]]

 [[ 86   8  32]
  [ 88   5  23]
  [ 89   7  27]
  ...
  [202 184 147]
  [200 181 145]
  [201 183 143]]]
[[ 67  84  70 ...  89 100 119]
 [ 70  86  74 ...  93  99 118]
 [ 73  86  74 ...  96 101 117]
 ...
 [ 46  46  45 ... 183 185 184]
 [ 45  46  46 ... 186 184 184]
 [ 46  46  48 ... 184 182 182]]


### Question 2 :

In [162]:
# Chaque matrice représente un Pixel, la matrice 3*3 est donc la représentation RGB de l'image
# Pour l'image 2 ce n'est pas déterminé par RGB mais par la couleur du pixel entre 0 et 255, d'ou la différence des matrices.

Ir = np.array([])
Ig = np.array([])
Ib = np.array([])
print(len(I1))
for i in range(len(I1)):
    np.append(Ir,I1[i][0])
    print(I1[i][0])
    np.append(Ig,I1[i][1])
    np.append(Ib,I1[i][2])

print(Ir)
imgR = Image.fromarray(Ir, 'RGB')
imgR.show()

512
[122  26  40]
[124  33  42]
[126  38  46]
[123  14  46]
[126  27  47]
[122  33  42]
[126  28  40]
[128  16  45]
[125  14  35]
[123  16  38]
[122  20  36]
[126  18  38]
[127  34  30]
[128  17  34]
[122  10  36]
[124  24  35]
[128  13  35]
[128  22  25]
[124  22  36]
[130  30  16]
[130  35  35]
[127  30  40]
[127  27  34]
[134  44  40]
[126  37  39]
[131  28  44]
[130  36  45]
[135  40  50]
[137  39  40]
[136  43  54]
[136  49  57]
[142  51  66]
[135  53  66]
[143  59  66]
[145  65  70]
[146  64  70]
[147  61  63]
[144  71  72]
[143  64  70]
[145  70  74]
[142  72  75]
[143  73  72]
[144  72  74]
[148  83  79]
[147  81  78]
[150  83  81]
[145  80  84]
[152  80  84]
[150  86  81]
[151  83  85]
[147  82  81]
[148  83  84]
[147  85  84]
[152  89  91]
[155  91  97]
[153  90  93]
[151  82  87]
[158  90  84]
[153  89  86]
[153  91  90]
[152  86  91]
[157  91  91]
[160  97  98]
[154  92  92]
[155  88  90]
[156  90  91]
[154  91 103]
[155  93  98]
[152  91  96]
[158  90  86]
[157  86  84]
[1

SystemError: tile cannot extend outside image